hosts:
  - domain: www.edibleforestgarden.ca
    path: /
    #base: /home/steve/networknt/light-config-test/light-router/virtual-host/edibleforestgarden/build
    base: /edibleforestgarden/build
    transferMinSize: 10245760
    directoryListingEnabled: false
  - domain: taiji.io
    path: /
    #base: /home/steve/networknt/light-config-test/light-router/virtual-host/taiji/build
    base: /taiji/build
    transferMinSize: 10245760
    directoryListingEnabled: false
  - domain: lightapi.net
    path: /
    #base: /home/steve/networknt/light-config-test/light-router/virtual-host/lightapi/build
    base: /lightapi/build
    transferMinSize: 10245760
    directoryListingEnabled: false
