# Workspace that is used for this operation. Most of time, this is done on local.
workspace: releasemaven_2_0_x
# release version that is used to generate changelog. This need to be changed every time
version: 2.0.0
# github organization as the token is bound to the org in changelog generator. This
# means that you can only release multiple repositories within the same org each time.
organization: networknt
# You can skip checkout if you are sure that the code in workspace are the latest and
# you just want to repeat the release process due to some environmental issue before.
skip_checkout: false
# You can skip the last release step so that you can double check the merged result.
skip_release: false
# clone and switch to develop branch / checkout and pull from develop branch
checkout:
  - branch: jdk11
    repository:
    - git@github.com:networknt/light-4j.git
    - git@github.com:networknt/json-overlay.git
    - git@github.com:networknt/openapi-parser.git
    - git@github.com:networknt/light-rest-4j.git
    # - git@github.com:networknt/light-graphql-4j.git
    # - git@github.com:networknt/light-hybrid-4j.git
    # - git@github.com:networknt/light-codegen.git
    # - git@github.com:networknt/light-eventuate-4j.git
    # - git@github.com:networknt/light-tram-kafka.git
    # - git@github.com:networknt/light-tram-4j.git
    # - git@github.com:networknt/light-saga-4j.git
    # - git@github.com:networknt/light-session-4j.git
    # - git@github.com:networknt/light-spa-4j.git
    # - git@github.com:networknt/light-proxy.git
    # - git@github.com:networknt/light-router.git
    # - git@github.com:networknt/light-oauth2.git
    # - git@github.com:networknt/light-tokenization.git
    # - git@github.com:networknt/light-consumer-4j.git
    # - git@github.com:networknt/light-example-4j.git
    # - git@github.com:networknt/light-docker.git
    # - git@github.com:networknt/light-bot.git
    # - git@github.com:networknt/light-config-server.git
    # - git@github.com:networknt/light-portal.git
    # - git@github.com:networknt/light-workflow-4j.git
    # - git@github.com:networknt/light-spring-boot.git

# generate changelog.md from github issues and check in
# release to maven central
# merge the changelog.md to develop branch
# publish the release to github repository
release:
  - light-4j
  - json-overlay
  - openapi-parser
  - light-rest-4j
#   - light-graphql-4j
#   - light-hybrid-4j
#   - light-codegen
#   - light-eventuate-4j
#   - light-tram-kafka
#   - light-tram-4j
#   - light-saga-4j
#   - light-session-4j
#   - light-spa-4j
#   - light-consumer-4j
#   - light-router
#   - light-proxy
#   - light-spring-boot

