version: '2'

services:

  light-router:
    image:  networknt/light-router:latest
    networks:
    - localnet
    ports:
    - 8443:8443
    volumes:
    - ./dev:/config
    - ./lightapi/build:/lightapi/build
#
# Networks
#
networks:
    localnet:
        # driver: bridge
        external: true
